"use strict";
exports.__esModule = true;
var Professional_1 = require("./Professional");
var Movie_1 = require("./Movie");
var a = new Professional_1.Professional("juan", 33, "terror", 89, 190, "azul", "verdes", ".", false, "japones", 1, "actor");
var b = new Professional_1.Professional("pedro", 19, "accion", 55, 169, "castaño", "verdes", ".", false, "aleman", 0, "actor");
var c = new Professional_1.Professional("maria", 55, "sci-fi", 88, 192, "rubio", "marron", ".", true, "americano", 2, "director");
var d = new Professional_1.Professional("rebeca", 33, "accion", 59, 175, "rubio", "azul", ".", false, "mejicana", 0, "actor");
a.getprofessional();
var professional1 = [a, b, c, d];
var Movie1 = new Movie_1.Movie("Encanto", 2, "española", "terror");
console.log(Movie1.printAll());
